Load Balancer WIP
kubecost/cost-model pull request #743
Opened 2021-03-18 01:26 UTC by Sean-Holcomb

2021-03-21 20:29 UTC, AjayTripathy commented
Could you explain where the costs are being allocated a bit more? The loadbalancer cost gets placed into the network category? Does it make sense to put it on a new, separate category called "LoadBalancer"? Do we have the ability to disentangle pod network egress costs from loadbalancers in this setup?

2021-03-22 15:03 UTC, nikovacevic requested changes
Great start, looking solid. I see Ajay and I had the same question about schema haha.

I would also say that more rigorous testing should be required. Can we confirm that this works for at least two load balancers? And perhaps we can test the period of time where a load balancer is created, and then removed some amount of time later, to make sure that all the numbers add up for the full lifecycle?

2021-03-22 15:03 UTC, nikovacevic commented on pkg/costmodel/allocation.go
> +			alloc.NetworkCost += lb.Cost * hours / totalHours
Did we end up just deciding to lump this into `NetworkCost`, or should we add a `LBCost` field? I would probably advocate for the latter. @AjayTripathy @mbolt35

2021-03-22 15:03 UTC, nikovacevic commented on pkg/costmodel/allocation.go
> +			hours := e.Sub(s).Hours()
Might want to consider a negative-value check here

2021-03-22 15:03 UTC, nikovacevic commented on pkg/costmodel/allocation.go
> +	Cost float64
Also, a public struct should be commented. Does your IDE give you warnings about that?

2021-03-23 01:07 UTC, Sean-Holcomb commented
I separated Load Balancer costs into their own category, and did the updates Niko suggested. Still have not gotten to the more robust testing that Niko outlined

2021-03-23 19:43 UTC, nikovacevic commented
Thanks for the update @Sean-Holcomb. Let me know if I can help with anything!

Also, planting a flag to talk about `bingen` soon. I see you have changes committed to the codec, but they're so marginal that I can't tell if you used the code generator or did that manually. (If you are already on top of the code generator, then kudos!) At any rate, we'll need to bump the version of the codec, too, and any of use (@AjayTripathy, @mbolt35, and myself) can help with that.

2021-03-30 23:17 UTC, Sean-Holcomb commented
Multi-load balancer test: 
From March 23rd-25th there were two load balancers running on the cluster with the 24th being the only day where both load balancers were running the entire day. As expected, over the course of this time period the load balancer cost is elevated. 
![Screen Shot 2021-03-30 at 3 48 27 PM](https://user-images.githubusercontent.com/12225425/113067644-95790380-9171-11eb-83e8-ab4f8e084268.png)
For reference the cost on the 20th-22nd were constant at .60 per day while only a single LB was running on the cluster. 
![Screen Shot 2021-03-30 at 4 05 10 PM](https://user-images.githubusercontent.com/12225425/113067988-3d8ecc80-9172-11eb-9576-01b6fe94aa07.png)
And on the 24th when 2 load balancers were running all day the LB costs was 1.20
![Screen Shot 2021-03-30 at 3 48 56 PM](https://user-images.githubusercontent.com/12225425/113068041-55fee700-9172-11eb-9133-a58544123bb6.png)
In prometheus we can see two distinct signals for the kubecost_load_balancer_cost metric during the lifespan of the second load balancer. Both signals end on the 25th when the cluster went down

![Screen Shot 2021-03-30 at 4 13 15 PM](https://user-images.githubusercontent.com/12225425/113068443-28666d80-9173-11eb-9e3b-b795c4359168.png)

2021-03-30 23:49 UTC, Sean-Holcomb commented
Life-cycle test:
For this test the load balancer was running on the cluster for 24 hours 45 minutes 39 seconds or 24.761 hours
![Screen Shot 2021-03-30 at 4 33 30 PM](https://user-images.githubusercontent.com/12225425/113070095-9ceedb80-9176-11eb-83d7-921bea168ace.png)
![Screen Shot 2021-03-30 at 4 33 40 PM](https://user-images.githubusercontent.com/12225425/113070099-9fe9cc00-9176-11eb-805d-616fee858e02.png)
with an hourly cost of $0.025 the expected LB cost for this time period is $0.619

![Screen Shot 2021-03-30 at 4 33 00 PM](https://user-images.githubusercontent.com/12225425/113070092-99f3eb00-9176-11eb-995f-a78ace328243.png)

2021-04-01 23:30 UTC, nikovacevic approved these changes
Awesome work on this, @Sean-Holcomb. Thanks for all the testing, too; it makes a huge difference.

LGTM!

2021-04-01 23:32 UTC, merged