Config Path Overlap Fixes
kubecost/cost-model pull request #924
Opened 2021-09-08 21:08 UTC by mbolt35

## What does this PR change?
Removes all hard-coded paths which involve the default CONFIG_PATH environment variable, and replaces with the value from the env package. Since we do not allow the config path to be changed currently from the helm chart, there is currently no effect on the dependent code. However, as we push to build a more reliable configuration, these smaller fixes will become more valuable.

## How was this PR tested?
Helm deployment on AWS and observation.

2021-09-08 21:18 UTC, nikovacevic requested changes
Lil typo, then LGTM!

2021-09-08 21:18 UTC, nikovacevic commented on pkg/cloud/awsprovider.go
> +func getAtenaConfigFilePath() string {
Atena -> Athena :smile:

2021-11-15 17:51 UTC, michaelmdresser commented
Seems like a good change, @mbolt35 are you okay with resolving conflicts (or re-opening this PR) so it can be properly reviewed?

2021-11-15 18:36 UTC, mbolt35 commented
This is no longer required - will probably be rolled into a bigger change at some point. Thanks for the quick review :)

2021-11-15 18:36 UTC, closed without merging